<?php

namespace Plateforme\CatalogueBundle\Repository;

/**
 * AttributCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttributCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
