<?php

namespace Plateforme\CatalogueBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository {
  
  /**
   * Fonction pour rechercher les catégories parents (= celles qui n'ont pas de parent)
   */
  public function findParents() {
    $qb = $this->createQueryBuilder('c')
        ->Select('c')
        ->Where('c.categorie is NULL');
    return $qb->getQuery()->getResult();
  }
  
  /**
   * Fonction pour rechercher catégories enfants d'une catégorie
   */
  public function findEnfants($id) {
    $qb = $this->createQueryBuilder('c')
        ->Select('c')
        ->Where('c.categorie = :parent_id')
        ->setParameter('parent_id', $id);
    return $qb->getQuery()->getResult();
  }

}
