<?php

namespace Plateforme\CatalogueBundle\Repository;

/**
 * DeclinaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclinaisonRepository extends \Doctrine\ORM\EntityRepository {

  /**
   * Recherche d'une declinaison à partir d'une combinaison
   */
  public function findOneByCombinaisons($valeurs_recu) {
    $qb = $this->createQueryBuilder('d')
        ->Select('d')
        ->Where('d.produit = :produit')
        ->andWhere('d.combinaison IN (:combinaisons)')
        ->setParameter('produit', $valeurs_recu['produit_id'])
        ->setParameter('combinaisons', $valeurs_recu);
    $qb->setMaxResults(1);
    
    return $qb->getQuery()->getOneOrNullResult();
  }

}
