# app/config/security.yml
# @see http://symfony.com/doc/current/security.html
security:
    encoders:
        Plateforme\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_EMPLOYE:                       [ROLE_CLIENT]
        ROLE_WEBMASTER:                     [ROLE_EMPLOYE]
        ROLE_ADMIN:                         [ROLE_WEBMASTER]
        ROLE_SUPER_ADMIN:                   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
          id:               fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: plateforme_user_login
                check_path: fos_user_security_check
            logout:
                path:       fos_user_security_logout
                target:     plateforme_user_login
            remember_me:
                secret:     %secret%

    access_control:
        - { path: ^/admin, roles: ROLE_EMPLOYE}
