<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * FAQCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FAQCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
