<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * GroupeContributeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeContributeurRepository extends \Doctrine\ORM\EntityRepository {

}