<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * PageApprobationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageApprobationRepository extends \Doctrine\ORM\EntityRepository {

}
