<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * PageStandardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageStandardRepository extends \Doctrine\ORM\EntityRepository
{
  
  /**
   * Renvoie la dernière version d'une page
   */
  public function getAllPages() {
    $qb = $this->createQueryBuilder('p');
    $qb->leftJoin('p.version', 'v');
    $qb->orderBy('p.updated', 'DESC');
    $qb->addGroupBy('v.idGroupe');

    return $qb->getQuery()->getResult();
  }
  
}
