<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * PageFAQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageFAQRepository extends \Doctrine\ORM\EntityRepository
{
  
}
