<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * PageActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageActualiteRepository extends \Doctrine\ORM\EntityRepository
{
  
}
