<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * PageContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageContactRepository extends \Doctrine\ORM\EntityRepository
{
  
}
