<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * PageStandardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageStandardRepository extends \Doctrine\ORM\EntityRepository
{
  
  /**
   * Renvoie la dernière version d'une page
   */
  public function getAllPages() {
    $qb = $this->createQueryBuilder('p');
    //$qb->leftJoin('p.groupe', 'g');
    //$qb->orderBy('p.updated', 'DESC');
    //$qb->addGroupBy('g.id');

    return $qb->getQuery()->getResult();
  }
  
}
