<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * PageCommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCommentaireRepository extends \Doctrine\ORM\EntityRepository {

}
