<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository {

  /**
   * Renvoie la dernière version d'une page
   */
  public function getAllPages() {
    $qb = $this->createQueryBuilder('p');
    // en cas d'erreur, executer dans phpmyadmin: SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
    $qb->orderBy('p.id', 'DESC');

    return $qb->getQuery()->getResult();
  }

}
