<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * PageStandardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageStandardRepository extends \Doctrine\ORM\EntityRepository
{
  
}
