<?php

namespace Plateforme\CoreBundle\Repository;

/**
 * ReseauxSociauxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReseauxSociauxRepository extends \Doctrine\ORM\EntityRepository
{
}
