################################################################################
# TUNNEL D'ACHAT
################################################################################
plateforme_ecommerce_tunnel_panier:
    path:  /tunnel-achat
    defaults: { _controller: PlateformeEcommerceBundle:Panier:panier }
plateforme_ecommerce_tunnel_authentification:
    path:  /tunnel-achat/authentification
    defaults: { _controller: PlateformeEcommerceBundle:Tunnel:authentification }
plateforme_ecommerce_tunnel_livraison:
    path:  /tunnel-achat/livraison
    defaults: { _controller: PlateformeEcommerceBundle:Livraison:livraison }
plateforme_ecommerce_tunnel_livraison_choix:
    path:  /tunnel-achat/livraison-choix
    defaults: { _controller: PlateformeEcommerceBundle:Livraison:choix }
    methods: [post]
plateforme_ecommerce_tunnel_validation:
    path:  /tunnel-achat/validation
    defaults: { _controller: PlateformeEcommerceBundle:Tunnel:validation }
plateforme_ecommerce_commandeligne_add:
    path:  /commandeligne-add/{id}
    defaults: { _controller: PlateformeEcommerceBundle:Panier:add }
plateforme_ecommerce_commandeligne_delete:
    path:  /commandeligne-delete/{id}
    defaults: { _controller: PlateformeEcommerceBundle:Panier:delete }
plateforme_ecommerce_panier_vider:
    path:  /panier-vider
    defaults: { _controller: PlateformeEcommerceBundle:Panier:vider }
plateforme_ecommerce_livraison_suppression:
    path:  /livraison/adresse/suppression/{id}
    defaults: { _controller: PlateformeEcommerceBundle:Livraison:adresseSuppression }
################################################################################
# TARIF LAPOSTE
################################################################################
plateforme_ecommerce_tariflapostelettre_crud:
    path:      /admin/tarifs-la-poste-lettre
    defaults: { _controller: PlateformeEcommerceBundle:TarifLaposteLettre:crud }
plateforme_ecommerce_tariflapostelettre_add:
    path:      /admin/tarifs-la-poste-lettre/add
    defaults: { _controller: PlateformeEcommerceBundle:TarifLaposteLettre:add }
plateforme_ecommerce_tariflapostelettre_tarif:
    path:  /livraison/tarifs-la-poste-lettre
    defaults: { _controller: PlateformeEcommerceBundle:TarifLaposteLettre:tarif }
    methods: [post]
plateforme_ecommerce_tariflapostelettre_edit:
    path:      /admin/tarifs-la-poste-lettre/edit/{id}
    defaults: { _controller: PlateformeEcommerceBundle:TarifLaposteLettre:edit }
    requirements:
        id: \d*
plateforme_ecommerce_tariflapostelettre_delete:
    path:      /admin/tarifs-la-poste-lettre/delete/{id}
    defaults: { _controller: PlateformeEcommerceBundle:TarifLaposteLettre:delete }
    requirements:
        id: \d*
plateforme_ecommerce_tariflapostecolissimo_crud:
    path:      /admin/tarifs-la-poste-colissimo
    defaults: { _controller: PlateformeEcommerceBundle:TarifLaposteColissimo:crud }
plateforme_ecommerce_tariflapostecolissimo_add:
    path:      /admin/tarifs-la-poste-colissimo/add
    defaults: { _controller: PlateformeEcommerceBundle:TarifLaposteColissimo:add }
plateforme_ecommerce_tariflapostecolissimo_tarif:
    path:  /livraison/tarifs-la-poste-colissimo
    defaults: { _controller: PlateformeEcommerceBundle:TarifLaposteColissimo:tarif }
    methods: [post]
plateforme_ecommerce_tariflapostecolissimo_edit:
    path:      /admin/tarifs-la-poste-colissimo/edit/{id}
    defaults: { _controller: PlateformeEcommerceBundle:TarifLaposteColissimo:edit }
    requirements:
        id: \d*
plateforme_ecommerce_tariflapostecolissimo_delete:
    path:      /admin/tarifs-la-poste-colissimo/delete/{id}
    defaults: { _controller: PlateformeEcommerceBundle:TarifLaposteColissimo:delete }
    requirements:
        id: \d*
plateforme_ecommerce_retrait_tarif:
    path:  /livraison/tarifs-retrait
    defaults: { _controller: PlateformeEcommerceBundle:LivraisonRetrait:tarif }
    methods: [post]
################################################################################
# COMMANDES
################################################################################
plateforme_ecommerce_commandes_crud:
    path:      /admin/commandes
    defaults:
        _controller: PlateformeEcommerceBundle:Commande:crud
plateforme_ecommerce_commandes_add:
    path:      /admin/commandes/add
    defaults:
        _controller: PlateformeEcommerceBundle:Commande:add
plateforme_ecommerce_commandes_edit:
    path:      /admin/commandes/edit/{id}
    defaults:
        _controller: PlateformeEcommerceBundle:Commande:edit
    requirements:
        id: \d*
plateforme_ecommerce_commandes_status:
    path:      /admin/commandes/status/{id}
    defaults:
        _controller: PlateformeEcommerceBundle:Commande:status
    requirements:
        id: \d*
    methods: [post]
plateforme_ecommerce_commandes_delete:
    path:      /admin/commandes/delete/{id}
    defaults:
        _controller: PlateformeEcommerceBundle:Commande:delete
    requirements:
        id: \d*
################################################################################
# ETATS DE PAIEMENT
################################################################################
plateforme_ecommerce_etatspaiement_crud:
    path:      /admin/etats-paiement
    defaults:
        _controller: PlateformeEcommerceBundle:EtatPaiement:crud
plateforme_ecommerce_etatspaiement_add:
    path:      /admin/etats-paiement/add
    defaults:
        _controller: PlateformeEcommerceBundle:EtatPaiement:add
plateforme_ecommerce_etatspaiement_edit:
    path:      /admin/etats-paiement/edit/{id}
    defaults:
        _controller: PlateformeEcommerceBundle:EtatPaiement:edit
    requirements:
        id: \d*
plateforme_ecommerce_etatspaiement_delete:
    path:      /admin/etats-paiement/delete/{id}
    defaults:
        _controller: PlateformeEcommerceBundle:EtatPaiement:delete
    requirements:
        id: \d*
################################################################################
# ETATS DE LIVRAISON
################################################################################
plateforme_ecommerce_etatslivraison_crud:
    path:      /admin/etats-livraison
    defaults:
        _controller: PlateformeEcommerceBundle:EtatLivraison:crud
plateforme_ecommerce_etatslivraison_add:
    path:      /admin/etats-livraison/add
    defaults:
        _controller: PlateformeEcommerceBundle:EtatLivraison:add
plateforme_ecommerce_etatslivraison_edit:
    path:      /admin/etats-livraison/edit/{id}
    defaults:
        _controller: PlateformeEcommerceBundle:EtatLivraison:edit
    requirements:
        id: \d*
plateforme_ecommerce_etatslivraison_delete:
    path:      /admin/etats-livraison/delete/{id}
    defaults:
        _controller: PlateformeEcommerceBundle:EtatLivraison:delete
    requirements:
        id: \d*