services:
    tva:
        class: Plateforme\EcommerceBundle\Twig\Extension\TvaExtension
        tags:
            - { name: twig.extension }
    montantTva:
        class: Plateforme\EcommerceBundle\Twig\Extension\MontantTvaExtension
        tags:
            - { name: twig.extension }