services:
    ht:
        class: Plateforme\EcommerceBundle\Twig\Extension\HTExtension
        tags:
            - { name: twig.extension }
    ttc:
        class: Plateforme\EcommerceBundle\Twig\Extension\TTCExtension
        tags:
            - { name: twig.extension }
    tva:
        class: Plateforme\EcommerceBundle\Twig\Extension\TVAExtension
        tags:
            - { name: twig.extension }
    mode_paiement:
        class: Plateforme\EcommerceBundle\Twig\Extension\ModePaiementExtension
        tags:
            - { name: twig.extension }
    mode_livraison:
        class: Plateforme\EcommerceBundle\Twig\Extension\ModeLivraisonExtension
        tags:
            - { name: twig.extension }