################################################################################
# PRODUITS
################################################################################
plateforme_catalogue_produits_index:
    path:      /produits
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:index
plateforme_catalogue_produits_crud:
    path:      /admin/produits
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:crud
plateforme_catalogue_produits_add:
    path:      /admin/produits/add
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:add
plateforme_catalogue_produits_edit:
    path:      /admin/produits/edit/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:edit
    requirements:
        id: \d*
plateforme_catalogue_produits_edit_declinaisons:
    path:      /admin/produits/edit-declinaisons/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:editDeclinaisons
    requirements:
        id: \d*
plateforme_catalogue_produits_delete_declinaison:
    path:      /admin/produits/delete-declinaison/{id}/{declinaison_id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:deleteDeclinaison
    requirements:
        id: \d*
plateforme_catalogue_produits_delete_declinaisons:
    path:      /admin/produits/delete-declinaisons/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:deleteDeclinaisons
    requirements:
        id: \d*
plateforme_catalogue_produits_clone:
    path:      /admin/produits/clone/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:clone
    requirements:
        id: \d*
plateforme_catalogue_produits_delete:
    path:      /admin/produits/delete/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:delete
    requirements:
        id: \d*
plateforme_catalogue_produits_view:
    path:      /produits/{slug}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:view
plateforme_catalogue_produits_json:
    path:      /search/produits/json
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:json

################################################################################
# MARQUES
################################################################################
plateforme_catalogue_marques_index:
    path:      /marques
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:index
plateforme_catalogue_marques_crud:
    path:      /admin/marques
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:crud
plateforme_catalogue_marques_add:
    path:      /admin/marques/add
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:add
plateforme_catalogue_marques_edit:
    path:      /admin/marques/edit/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:edit
    requirements:
        id: \d*
plateforme_catalogue_marques_clone:
    path:      /admin/marques/clone/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:clone
    requirements:
        id: \d*
plateforme_catalogue_marques_delete:
    path:      /admin/marques/delete/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:delete
    requirements:
        id: \d*
plateforme_catalogue_marques_view:
    path:      /marques/{slug}
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:view

################################################################################
# ATTRIBUTS
################################################################################
plateforme_catalogue_attributs_categories_crud:
    path:      /admin/attributs
    defaults:
        _controller: PlateformeCatalogueBundle:AttributCategorie:crud
plateforme_catalogue_attributs_categories_add:
    path:      /admin/attributs/add
    defaults:
        _controller: PlateformeCatalogueBundle:AttributCategorie:add
plateforme_catalogue_attributs_categories_edit:
    path:      /admin/attributs/edit/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:AttributCategorie:edit
    requirements:
        id: \d*
plateforme_catalogue_attributs_categories_delete:
    path:      /admin/attributs/delete/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:AttributCategorie:delete
    requirements:
        id: \d*
plateforme_catalogue_attributs_categories_categorie:
    path:      /admin/attributs/categorie/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Attribut:crud
    requirements:
        id: \d*
plateforme_catalogue_attributs_categories_categorie_add:
    path:      /admin/attributs/categorie/{id}/add
    defaults:
        _controller: PlateformeCatalogueBundle:Attribut:add
    requirements:
        id: \d*
plateforme_catalogue_attributs_categories_categorie_edit:
    path:      /admin/attributs/categorie/{categorie_id}/edit/{attribut_id}
    defaults:
        _controller: PlateformeCatalogueBundle:Attribut:edit
    requirements:
        id: \d*
plateforme_catalogue_attributs_categories_categorie_delete:
    path:      /admin/attributs/categorie/{categorie_id}/delete/{attribut_id}
    defaults:
        _controller: PlateformeCatalogueBundle:Attribut:delete