################################################################################
# PRODUITS
################################################################################
plateforme_catalogue_produits_crud:
    path:      /admin/produits
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:crud
plateforme_catalogue_produits_add:
    path:      /admin/produits/add
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:add
plateforme_catalogue_produits_edit:
    path:      /admin/produits/edit/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:edit
    requirements:
        id: \d*
plateforme_catalogue_produits_edit_declinaisons:
    path:      /admin/produits/edit-declinaisons/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:editDeclinaisons
    requirements:
        id: \d*
plateforme_catalogue_produits_edit_declinaison:
    path:      /admin/produits/edit-declinaison/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:editDeclinaison
    requirements:
        id: \d*
    methods: [post]
plateforme_catalogue_produits_delete_declinaison:
    path:      /admin/produits/delete-declinaison/{id}/{declinaison_id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:deleteDeclinaison
    requirements:
        id: \d*
plateforme_catalogue_produits_delete_declinaisons:
    path:      /admin/produits/delete-declinaisons/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:deleteDeclinaisons
    requirements:
        id: \d*
plateforme_catalogue_produits_clone:
    path:      /admin/produits/clone/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:clone
    requirements:
        id: \d*
plateforme_catalogue_produits_delete:
    path:      /admin/produits/delete/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:delete
    requirements:
        id: \d*
plateforme_catalogue_produits_addcategorie:
    path:      /admin/produits/add-categorie/{id_produit}/{id_categorie}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:addCategorie
plateforme_catalogue_produits_removecategorie:
    path:      /admin/produits/remove-categorie/{id_produit}/{id_categorie}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:removeCategorie
plateforme_catalogue_produits_view:
    path:      /produits/{slug}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:view
plateforme_catalogue_produits_majfiche:
    path:      /produits-majfiche
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:majFicheProduit
plateforme_catalogue_produits_json:
    path:      /recherche/produits
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:json
plateforme_catalogue_produits_resultats:
    path:      /recherche/resultats-produits/{term}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:resultats
################################################################################
# CATEGORIE
################################################################################
plateforme_catalogue_categories_index:
    path:      /nos-produits
    defaults:
        _controller: PlateformeCatalogueBundle:Categorie:index
plateforme_catalogue_categories_view:
    path:      /categories/{slug}
    defaults:
        _controller: PlateformeCatalogueBundle:Categorie:view
plateforme_catalogue_categories_crud:
    path:      /admin/categories
    defaults:
        _controller: PlateformeCatalogueBundle:Categorie:crud
plateforme_catalogue_categories_enfants_crud:
    path:      /admin/categories/enfants/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Categorie:crudEnfants
    requirements:
        id: \d*
plateforme_catalogue_categories_add:
    path:      /admin/categories/add
    defaults:
        _controller: PlateformeCatalogueBundle:Categorie:add
plateforme_catalogue_categories_edit:
    path:      /admin/categories/edit/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Categorie:edit
    requirements:
        id: \d*
plateforme_catalogue_categories_clone:
    path:      /admin/categories/clone/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Categorie:clone
    requirements:
        id: \d*
plateforme_catalogue_categories_delete:
    path:      /admin/categories/delete/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Categorie:delete
    requirements:
        id: \d*
plateforme_catalogue_categories_json:
    path:      /recherche/categories
    defaults:
        _controller: PlateformeCatalogueBundle:Categorie:json

################################################################################
# MARQUES
################################################################################
plateforme_catalogue_marques_index:
    path:      /marques
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:index
plateforme_catalogue_marques_crud:
    path:      /admin/marques
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:crud
plateforme_catalogue_marques_add:
    path:      /admin/marques/add
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:add
plateforme_catalogue_marques_edit:
    path:      /admin/marques/edit/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:edit
    requirements:
        id: \d*
plateforme_catalogue_marques_clone:
    path:      /admin/marques/clone/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:clone
    requirements:
        id: \d*
plateforme_catalogue_marques_delete:
    path:      /admin/marques/delete/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:delete
    requirements:
        id: \d*
plateforme_catalogue_marques_view:
    path:      /marques/{slug}
    defaults:
        _controller: PlateformeCatalogueBundle:Marque:view

################################################################################
# ATTRIBUTS
################################################################################
plateforme_catalogue_attributs_categories_crud:
    path:      /admin/attributs
    defaults:
        _controller: PlateformeCatalogueBundle:AttributCategorie:crud
plateforme_catalogue_attributs_categories_add:
    path:      /admin/attributs/add
    defaults:
        _controller: PlateformeCatalogueBundle:AttributCategorie:add
plateforme_catalogue_attributs_categories_edit:
    path:      /admin/attributs/edit/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:AttributCategorie:edit
    requirements:
        id: \d*
plateforme_catalogue_attributs_categories_delete:
    path:      /admin/attributs/delete/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:AttributCategorie:delete
    requirements:
        id: \d*
plateforme_catalogue_attributs_categories_categorie:
    path:      /admin/attributs/categorie/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Attribut:crud
    requirements:
        id: \d*
plateforme_catalogue_attributs_categories_categorie_add:
    path:      /admin/attributs/categorie/{id}/add
    defaults:
        _controller: PlateformeCatalogueBundle:Attribut:add
    requirements:
        id: \d*
plateforme_catalogue_attributs_categories_categorie_edit:
    path:      /admin/attributs/categorie/{categorie_id}/edit/{attribut_id}
    defaults:
        _controller: PlateformeCatalogueBundle:Attribut:edit
    requirements:
        id: \d*
plateforme_catalogue_attributs_categories_categorie_delete:
    path:      /admin/attributs/categorie/{categorie_id}/delete/{attribut_id}
    defaults:
        _controller: PlateformeCatalogueBundle:Attribut:delete