################################################################################
# PRODUITS
################################################################################
plateforme_catalogue_produits_index:
    path:      /produits
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:index
        
plateforme_catalogue_produits_crud:
    path:      /admin/pages/produits
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:crud

plateforme_catalogue_produits_add:
    path:      /admin/pages/produits/add
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:add

plateforme_catalogue_produits_edit:
    path:      /admin/pages/produits/edit/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:edit
    requirements:
        id: \d*

plateforme_catalogue_produits_clone:
    path:      /admin/pages/produits/clone/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:clone
    requirements:
        id: \d*

plateforme_catalogue_produits_delete:
    path:      /admin/pages/produits/delete/{id}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:delete
    requirements:
        id: \d*

plateforme_catalogue_produits_view:
    path:      /produits/{slug}
    defaults:
        _controller: PlateformeCatalogueBundle:Produit:view