services:
    catalogue_attribut:
        class: Plateforme\CatalogueBundle\Twig\Extension\AttributCategorieExtension
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }