<?php

namespace Plateforme\EcommerceBundle\Repository;

/**
 * EtatPaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatPaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
