<?php

namespace Plateforme\EcommerceBundle\Repository;

/**
 * TarifLaposteRecommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifLaposteRecommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
