<?php

namespace Plateforme\EcommerceBundle\Repository;

/**
 * TarifLaposteColissimoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifLaposteColissimoRepository extends \Doctrine\ORM\EntityRepository
{
}
