<?php

namespace Plateforme\EcommerceBundle\Repository;

/**
 * TarifLaposteLettreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifLaposteLettreRepository extends \Doctrine\ORM\EntityRepository
{
  public function findTarifMinimum()
  {
    $qb = $this->createQueryBuilder('t');
    $qb
      ->select('t.tarif')
      ->orderBy('t.tarif', 'ASC')
    ;
    return $qb
      ->setMaxResults(1)
      ->getQuery()
      ->getSingleResult()
    ;
  }
}
