<?php

namespace Plateforme\EcommerceBundle\Repository;

/**
 * TarifLaposteLettreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifLaposteLettreRepository extends \Doctrine\ORM\EntityRepository
{
}
