################################################################################
# PAGE
################################################################################
plateforme_core_pages_publication:
    path:      /admin/pages/publication
    defaults: { _controller: PlateformeCoreBundle:Page:publication }
    methods: [post]
################################################################################
# VARIABLES
################################################################################
plateforme_core_variables_crud:
    path:      /admin/variables
    defaults:
        _controller: PlateformeCoreBundle:Variable:crud

plateforme_core_variables_add:
    path:      /admin/variables/add
    defaults:
        _controller: PlateformeCoreBundle:Variable:add

plateforme_core_variables_edit:
    path:      /admin/variables/edit/{id}
    defaults:
        _controller: PlateformeCoreBundle:Variable:edit
    requirements:
        id: \d*

plateforme_core_variables_delete:
    path:      /admin/variables/delete/{id}
    defaults:
        _controller: PlateformeCoreBundle:Variable:delete
    requirements:
        id: \d*

################################################################################
# MAINTENANCE
################################################################################
plateforme_core_maintenance_index:
    path:      /admin/maintenance
    defaults:
        _controller: PlateformeCoreBundle:Maintenance:index

################################################################################
# PAGES
################################################################################
plateforme_core_contenu_crud:
    path:     /admin/contenu
    defaults: { _controller: PlateformeCoreBundle:Page:contenu}

################################################################################
# PAGE ACCUEIL
################################################################################
plateforme_core_homepage:
    path:     /
    defaults: { _controller: PlateformeCoreBundle:PageAccueil:index }
    
plateforme_core_homepage_edit:
    path:      /admin/pages/accueil/edit
    defaults:
        _controller: PlateformeCoreBundle:PageAccueil:edit
        
        
################################################################################
# PAGES STANDARDD
################################################################################
plateforme_core_page_pages_index:
    path:      /pages
    defaults:
        _controller: PlateformeCoreBundle:PageStandard:index
        
plateforme_core_page_pages_crud:
    path:      /admin/pages/standards
    defaults:
        _controller: PlateformeCoreBundle:PageStandard:crud

plateforme_core_page_pages_add:
    path:      /admin/pages/standards/add
    defaults:
        _controller: PlateformeCoreBundle:PageStandard:add

plateforme_core_page_pages_edit:
    path:      /admin/pages/standards/edit/{id}
    defaults:
        _controller: PlateformeCoreBundle:PageStandard:edit
    requirements:
        id: \d*

plateforme_core_page_pages_clone:
    path:      /admin/pages/pages/clone/{id}
    defaults:
        _controller: PlateformeCoreBundle:PageStandard:clone
    requirements:
        id: \d*

plateforme_core_page_pages_delete:
    path:      /admin/pages/pages/delete/{id}
    defaults:
        _controller: PlateformeCoreBundle:PageStandard:delete
    requirements:
        id: \d*

plateforme_core_page_pages_view:
    path:      /pages/{slug}
    defaults:
        _controller: PlateformeCoreBundle:PageStandard:view

################################################################################
# PAGE CONTACT
################################################################################
plateforme_core_page_contact_index:
    path:      /contact
    defaults:
        _controller: PlateformeCoreBundle:PageContact:index

################################################################################
# PAGE FAQ
################################################################################
plateforme_core_page_faq_index:
    path:     /faq
    defaults: { _controller: PlateformeCoreBundle:PageFAQ:index }
    
plateforme_core_page_faq_edit:
    path:      /admin/pages/faq/edit
    defaults:
        _controller: PlateformeCoreBundle:PageFAQ:edit
        
plateforme_core_page_faq_question_crud:
    path:      /admin/pages/faq/questions
    defaults:
        _controller: PlateformeCoreBundle:FAQQuestion:crud

plateforme_core_page_faq_question_add:
    path:      /admin/pages/faq/questions/add
    defaults:
        _controller: PlateformeCoreBundle:FAQQuestion:add

plateforme_core_page_faq_question_edit:
    path:      /admin/pages/faq/questions/edit/{id}
    defaults:
        _controller: PlateformeCoreBundle:FAQQuestion:edit
    requirements:
        id: \d*

plateforme_core_page_faq_question_delete:
    path:      /admin/pages/faq/questions/delete/{id}
    defaults:
        _controller: PlateformeCoreBundle:FAQQuestion:delete
    requirements:
        id: \d*

plateforme_core_page_faq_categorie_crud:
    path:      /admin/pages/faq/categories
    defaults:
        _controller: PlateformeCoreBundle:FAQCategorie:crud

plateforme_core_page_faq_categorie_add:
    path:      /admin/pages/faq/categories/add
    defaults:
        _controller: PlateformeCoreBundle:FAQCategorie:add

plateforme_core_page_faq_categorie_edit:
    path:      /admin/pages/faq/categories/edit/{id}
    defaults:
        _controller: PlateformeCoreBundle:FAQCategorie:edit
    requirements:
        id: \d*

plateforme_core_page_faq_categorie_delete:
    path:      /admin/pages/faq/categories/delete/{id}
    defaults:
        _controller: PlateformeCoreBundle:FAQCategorie:delete
    requirements:
        id: \d*
        
################################################################################
# PAGES ACTUALITES
################################################################################
plateforme_core_page_actualites_index:
    path:      /actualites
    defaults:
        _controller: PlateformeCoreBundle:PageActualite:index
        
plateforme_core_page_actualites_crud:
    path:      /admin/pages/actualites
    defaults:
        _controller: PlateformeCoreBundle:PageActualite:crud

plateforme_core_page_actualites_add:
    path:      /admin/pages/actualites/add
    defaults:
        _controller: PlateformeCoreBundle:PageActualite:add

plateforme_core_page_actualites_edit:
    path:      /admin/pages/actualites/edit/{id}
    defaults:
        _controller: PlateformeCoreBundle:PageActualite:edit
    requirements:
        id: \d*

plateforme_core_page_actualites_clone:
    path:      /admin/pages/actualites/clone/{id}
    defaults:
        _controller: PlateformeCoreBundle:PageActualite:clone
    requirements:
        id: \d*

plateforme_core_page_actualites_delete:
    path:      /admin/pages/actualites/delete/{id}
    defaults:
        _controller: PlateformeCoreBundle:PageActualite:delete
    requirements:
        id: \d*

plateforme_core_page_actualites_view:
    path:      /actualites/{slug}
    defaults:
        _controller: PlateformeCoreBundle:PageActualite:view

################################################################################
# PAGES ADRESSES
################################################################################
plateforme_core_page_adresses:
    path:      /profile/adresses
    defaults:
        _controller: PlateformeCoreBundle:Adresse:crud
        
plateforme_core_page_adresses_add:
    path:      /profile/adresses/add
    defaults:
        _controller: PlateformeCoreBundle:Adresse:add

plateforme_core_page_adresses_edit:
    path:      /profile/adresses/edit/{id}
    defaults:
        _controller: PlateformeCoreBundle:Adresse:edit
    requirements:
        id: \d*

plateforme_core_page_adresses_delete:
    path:      /profile/adresses/delete/{id}
    defaults:
        _controller: PlateformeCoreBundle:Adresse:delete
    requirements:
        id: \d*

        
################################################################################
# PARTAGE ET RÉSEAUX SOCIAUX
################################################################################
plateforme_core_reseaux_sociaux:
    path:     /admin/réseaux-sociaux
    defaults: { _controller: PlateformeCoreBundle:ReseauxSociaux:manage }
plateforme_core_share:
    path:     /réseaux-sociaux/share
    defaults: { _controller: PlateformeCoreBundle:ReseauxSociaux:share }
    methods: [post]
        
################################################################################
# PAGE ACCUEIL DU BACK OFFICE
################################################################################
plateforme_core_bo_homepage:
    path:     /admin
    defaults: { _controller: PlateformeCoreBundle:BackOffice:index }
    
plateforme_core_bo_pages:
    path:     /admin/pages
    defaults: { _controller: PlateformeCoreBundle:BackOffice:pages }
    
plateforme_core_bo_catalogue:
    path:     /admin/catalogue
    defaults: { _controller: PlateformeCoreBundle:BackOffice:catalogue }
    
plateforme_core_bo_configuration:
    path:     /admin/configuration
    defaults: { _controller: PlateformeCoreBundle:BackOffice:configuration }