services:
    core_page:
        class: Plateforme\CoreBundle\Services\PageService
        arguments: 
            - "@doctrine.orm.entity_manager"
            - "@=service('security.token_storage').getToken().getUser()"
            - "@router"